// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkBsHVKjoK809yBsfRmqey4DJ0hMgsaWs',
    appId: '1:664546609726:web:7b896ef51b9f993bd85f6f',
    messagingSenderId: '664546609726',
    projectId: 'jewelstack-cc698',
    authDomain: 'jewelstack-cc698.firebaseapp.com',
    storageBucket: 'jewelstack-cc698.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUXN-XMfPWVUXTJcgESlZyRaKyaF9Umnc',
    appId: '1:664546609726:android:0e3b54dac15e69c8d85f6f',
    messagingSenderId: '664546609726',
    projectId: 'jewelstack-cc698',
    storageBucket: 'jewelstack-cc698.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtWNqMC1Gzv3CuU0-XWkdOIxCmFcqROm4',
    appId: '1:664546609726:ios:3dff9183a8ce2185d85f6f',
    messagingSenderId: '664546609726',
    projectId: 'jewelstack-cc698',
    storageBucket: 'jewelstack-cc698.firebasestorage.app',
    iosBundleId: 'com.example.jewelstack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtWNqMC1Gzv3CuU0-XWkdOIxCmFcqROm4',
    appId: '1:664546609726:ios:3dff9183a8ce2185d85f6f',
    messagingSenderId: '664546609726',
    projectId: 'jewelstack-cc698',
    storageBucket: 'jewelstack-cc698.firebasestorage.app',
    iosBundleId: 'com.example.jewelstack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkBsHVKjoK809yBsfRmqey4DJ0hMgsaWs',
    appId: '1:664546609726:web:6c03384c55528f7ad85f6f',
    messagingSenderId: '664546609726',
    projectId: 'jewelstack-cc698',
    authDomain: 'jewelstack-cc698.firebaseapp.com',
    storageBucket: 'jewelstack-cc698.firebasestorage.app',
  );
}